api_version: 1
runtime: python27
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: pong.main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: MySQLdb
  version: latest

env_variables:
  INSTANCE_CONNECTION_NAME: "google.com:qh-pong:us-west1:pong2nd"
  CLOUD_SQL_USER: "root"
