"""empty message

Revision ID: 1fcf898291ca
Revises: 
Create Date: 2015-08-10 10:32:14.141678

"""

# revision identifiers, used by Alembic.
revision = '1fcf898291ca'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('playerA_name', sa.String(length=24), nullable=True),
    sa.Column('playerB_name', sa.String(length=24), nullable=True),
    sa.Column('scoreA', sa.Integer(), nullable=False),
    sa.Column('scoreB', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playerA_name'], ['users.name'], ),
    sa.ForeignKeyConstraint(['playerB_name'], ['users.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('users')
    ### end Alembic commands ###
