"""initial

Revision ID: b8444dd2beb
Revises: 
Create Date: 2015-07-22 01:16:31.523029

"""

# revision identifiers, used by Alembic.
revision = 'b8444dd2beb'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('playerA', sa.String(length=24), nullable=True),
    sa.Column('playerB', sa.String(length=24), nullable=True),
    sa.Column('scoreA', sa.Integer(), nullable=False),
    sa.Column('scoreB', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playerA'], ['users.name'], ),
    sa.ForeignKeyConstraint(['playerB'], ['users.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('users')
    ### end Alembic commands ###
